"""change

Revision ID: a912ece5ba9b
Revises: 
Create Date: 2024-12-10 23:10:38.282867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a912ece5ba9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.drop_constraint('Companies_user_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['company_name'])
        batch_op.drop_constraint('Companies_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('Job_Postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=False))
        batch_op.drop_constraint('Job_Postings_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Companies', ['company_name'], ['company_name'])
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Job_Postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('Job_Postings_company_id_fkey', 'Companies', ['company_id'], ['company_id'])
        batch_op.drop_column('company_name')

    with op.batch_alter_table('Companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('Companies_user_id_fkey', 'Users', ['user_id'], ['user_id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('Companies_user_id_key', ['user_id'])

    # ### end Alembic commands ###
